# -*- coding: utf-8 -*-
"""CIS 412 Group Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vQCi1px06HR2Z3MldbBFIAglTBBMkI1k
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from statsmodels.stats.outliers_influence import variance_inflation_factor
import statsmodels.api as sm
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.inspection import permutation_importance

df = pd.read_csv("/content/drive/MyDrive/CIS 412/gym_members_exercise_tracking.csv")
print(df.head())

#Describe data
df.info()
'''15 columns, 973 rows,
2 categorical variables(gender and workout_type), 13 numerical variables
0 missing values
'''
pd.set_option('display.max_columns', None)
df.describe(include='all')

for c in ['Gender', 'Workout_Type']:
    if c in df.columns:
        print(f"\nValue counts for {c}:")
        print(df[c].value_counts().head(10))
'''
Value counts for Gender:
Gender
Male      511
Female    462
Name: count, dtype: int64

Value counts for Workout_Type:
Workout_Type
Strength    258
Cardio      255
Yoga        239
HIIT        221
'''
#Feature engineering
df['duration_min'] = df['Session_Duration (hours)'] * 60
df['heart_rate'] = df['Avg_BPM']
df['intensity'] = df['heart_rate'] * df['duration_min']
df['HRR'] = df['Max_BPM'] - df['Resting_BPM']  # Heart Rate Reserve'

#Data exploration

plt.figure(figsize=(6,4))
sns.boxplot(x='Gender', y='Fat_Percentage', data=df)
plt.title('Fat % Distribution by Gender')
plt.ylabel('Fat Percentage')
plt.xlabel('Gender')
plt.tight_layout()

avg_fat_by_gender = df.groupby('Gender')['Fat_Percentage'].mean()
print(avg_fat_by_gender)

'''
Female 27.65
Male 22.5
'''

plt.figure(figsize=(7,5))
sns.boxplot(x='Workout_Type', y='Calories_Burned', data=df)
plt.title('Calories Burned by Workout Type')
plt.xlabel('Workout Type')
plt.ylabel('Calories Burned')
plt.tight_layout()

plt.figure(figsize=(6,5))
sns.scatterplot(data=df, x='Avg_BPM', y='Calories_Burned', hue='Gender', alpha=0.7)
plt.title('Avg BPM vs Calories Burned (by Gender)')
plt.tight_layout()

plt.figure(figsize=(7,5))
sns.scatterplot(x='duration_min', y='Calories_Burned', hue='Gender', data=df, alpha=0.7)
plt.title('Duration vs Calories Burned (by Gender)')
plt.xlabel('Duration (minutes)')
plt.ylabel('Calories Burned')
plt.tight_layout()

plt.figure(figsize=(7,5))
sns.scatterplot(x='intensity', y='Calories_Burned', hue='Gender', data=df, alpha=0.7)
plt.title('Intensity vs Calories Burned (by Gender)')
plt.xlabel('Intensity (Avg_BPM × Duration)')
plt.ylabel('Calories Burned')
plt.tight_layout()

# Compute correlation
numeric_df = df.select_dtypes(include=[np.number])
corr = numeric_df.corr()
mask = np.triu(np.ones_like(corr, dtype=bool))
plt.figure(figsize=(10,8))
sns.heatmap(corr, mask=mask, annot=True, fmt=".2f", cmap='coolwarm',
            square=False, cbar_kws={'shrink':0.5})
plt.title('Correlation Matrix (Lower Triangle Only)')
plt.tight_layout()

#VIF
vif_features = ['intensity', 'duration_min', 'heart_rate']

vif_features = [f for f in vif_features if f in df.columns]

def calculate_vif(df, features):
    X = df[features].dropna()
    X_const = sm.add_constant(X)

    vif_list = []
    for i, var in enumerate(features):
        vif_val = variance_inflation_factor(X_const.values, i + 1)  # +1 skips constant
        vif_list.append({'feature': var, 'VIF': vif_val})
    return pd.DataFrame(vif_list)

vif_df = calculate_vif(df, vif_features)

print("\nVIF Results:")
print(vif_df)

'''VIF Results:
        feature         VIF
0     intensity  116.967161
1  duration_min  102.168282
2    heart_rate   14.610883
'''
# VIF
# Intensity
# Histograms
# Do scaling before train test split


TARGET = 'Calories_Burned'
features = ['Age','Gender','BMI','heart_rate','HRR','duration_min',
            'Workout_Type','Fat_Percentage','Water_Intake (liters)',
    'Workout_Frequency (days/week)','Experience_Level']

# X and y from your dataframe
X_raw = df[features].copy()
y = df[TARGET].copy()

# identify numeric and categorical cols
num_feats = X_raw.select_dtypes(include=['number']).columns.tolist()
cat_feats = X_raw.select_dtypes(include=['object', 'category']).columns.tolist()

# transformer: scale numbers, one-hot encode categories
preproc = ColumnTransformer([
    ('num', StandardScaler(), num_feats),
    ('cat', OneHotEncoder(handle_unknown='ignore', sparse_output=False), cat_feats)
])

# fit on whole data (pre-split) and transform
X_processed_array = preproc.fit_transform(X_raw)

# build column names for processed dataframe
colnames = num_feats.copy()
if cat_feats:
    ohe = preproc.named_transformers_['cat']
    ohe_names = list(ohe.get_feature_names_out(cat_feats))
    colnames += ohe_names

X_processed = pd.DataFrame(X_processed_array, columns=colnames, index=X_raw.index)

# now split
X_train, X_test, y_train, y_test = train_test_split(X_processed, y, test_size=0.2, random_state=42)

X_test_raw = X_raw.loc[X_test.index].copy()

models = {
    'LinearRegression': Pipeline([
        ('lr', LinearRegression())
    ]),

    'RandomForest': Pipeline([
        ('rf', RandomForestRegressor(
            n_estimators=200,
            random_state=42,
            n_jobs=-1
        ))
    ])
}

# Train and evaluate
results = {}
for name, pipe in models.items():
    pipe.fit(X_train, y_train)
    y_pred = pipe.predict(X_test)
    mae = mean_absolute_error(y_test, y_pred)
    rmse = mean_squared_error(y_test, y_pred) ** 0.5
    r2 = r2_score(y_test, y_pred)
    results[name] = {'mae': mae, 'rmse': rmse, 'r2': r2, 'pipeline': pipe, 'y_pred': y_pred}


metrics = pd.DataFrame([
    {'model': name, 'mae': r['mae'], 'rmse': r['rmse'], 'r2': r['r2']}
    for name, r in results.items()
]).sort_values('rmse')

metrics

'''
              model        mae       rmse        r2
0  LinearRegression  29.767344  39.955480  0.980864
1      RandomForest  35.141615  46.145117  0.974476
'''

best_name = metrics.iloc[0]['model']
best_model = results[best_name]['pipeline']
best_pred = results[best_name]['y_pred']

# Actual vs Predicted plot
plt.figure(figsize=(6,6))
plt.scatter(y_test, best_pred, alpha=0.6)
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], '--', color='gray')
plt.xlabel("Actual Calories Burned")
plt.ylabel("Predicted Calories Burned")
plt.title(f"Actual vs Predicted ({best_name})")
plt.tight_layout()
plt.savefig(f"actual_vs_predicted_{best_name}.png")

# Feature importance for Linear Regression

feature_names = X_processed.columns.tolist()

# Get coefficients from the best linear regression model
coefs = best_model.named_steps['lr'].coef_

# Create DataFrame
fi = pd.DataFrame({
    'feature': feature_names,
    'coefficient': coefs
})

# Absolute values for ranking
fi['abs'] = fi['coefficient'].abs()

# Sort
fi = fi.sort_values('abs', ascending=False)

fi

# Gender subgroup performance
res = X_test_raw.copy()
res['actual'] = y_test.values
res['predicted'] = best_pred

gender_stats = []
for g in res['Gender'].unique():
    sub = res[res['Gender'] == g]
    mae = mean_absolute_error(sub['actual'], sub['predicted'])
    rmse = mean_squared_error(sub['actual'], sub['predicted'])** 0.5
    r2 = r2_score(sub['actual'], sub['predicted'])
    gender_stats.append({'Gender': g, 'MAE': mae, 'RMSE': rmse, 'R2': r2})

gender_df = pd.DataFrame(gender_stats)
print(gender_df)

res = X_test_raw.copy()                       # raw test features (contains 'Gender')
res = res.reset_index(drop=True)              # align indices with y_test and best_pred order
y_test_aligned = pd.Series(y_test.values)     # ensure same ordering/type
pred_aligned = pd.Series(best_pred)           # ensure same ordering/type

res['actual'] = y_test_aligned
res['predicted'] = pred_aligned

# Compute metrics by gender
gender_stats = []
for g in res['Gender'].unique():
    sub = res[res['Gender'] == g]
    if len(sub) == 0:
        continue
    mae = mean_absolute_error(sub['actual'], sub['predicted'])
    rmse = mean_squared_error(sub['actual'], sub['predicted'])**0.5
    r2 = r2_score(sub['actual'], sub['predicted'])
    gender_stats.append({'Gender': g, 'N': len(sub), 'MAE': mae, 'RMSE': rmse, 'R2': r2})

gender_df = pd.DataFrame(gender_stats).sort_values('Gender').reset_index(drop=True)
print(gender_df)

num_cols = ['Age','BMI','Avg_BPM','Max_BPM','Calories_Burned','duration_min','Fat_Percentage']

plt.figure(figsize=(12,10))
for i, col in enumerate(num_cols, 1):
    plt.subplot(3, 3, i)
    sns.histplot(df[col], kde=True, color='blue')
    plt.title(f"{col}Distribution")
plt.tight_layout()
