# -*- coding: utf-8 -*-
"""CIS 412 app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bhEUjYQ-yDle1TxQ49kV7FELLC2GhY8i
"""

import streamlit as st
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression

import matplotlib.pyplot as plt
import seaborn as sns


# -------------------------
# STREAMLIT PAGE CONFIG
# -------------------------
st.set_page_config(
    page_title="Gym Calories Burned Predictor",
    layout="wide"
)


# -------------------------
# DATA LOADING & MODELING
# -------------------------
@st.cache_data
def load_data(csv_path: str = "gym_members_exercise_tracking.csv") -> pd.DataFrame:
    """Load dataset and perform the same feature engineering as in the notebook."""
    df = pd.read_csv(csv_path)

    # Feature engineering
    df["duration_min"] = df["Session_Duration (hours)"] * 60
    df["heart_rate"] = df["Avg_BPM"]
    df["intensity"] = df["heart_rate"] * df["duration_min"]
    df["HRR"] = df["Max_BPM"] - df["Resting_BPM"]

    return df


@st.cache_resource
def train_model(df: pd.DataFrame):
    """Train Linear Regression model and return model & R² score."""
    TARGET = "Calories_Burned"

    # These features mirror what you used in your project
    features = [
        "Age",
        "Gender",
        "BMI",
        "heart_rate",
        "HRR",
        "duration_min",
        "Workout_Type",
        "Fat_Percentage",
        "Water_Intake (liters)",
        "Workout_Frequency (days/week)",
        "Experience_Level",
    ]

    X_raw = df[features].copy()
    y = df[TARGET].copy()

    # Split by type
    num_cols = X_raw.select_dtypes(include=["number"]).columns.tolist()
    cat_cols = X_raw.select_dtypes(include=["object", "category"]).columns.tolist()

    preproc = ColumnTransformer(
        transformers=[
            ("num", StandardScaler(), num_cols),
            ("cat", OneHotEncoder(handle_unknown="ignore"), cat_cols),
        ]
    )

    model = Pipeline(
        steps=[
            ("preprocessor", preproc),
            ("regressor", LinearRegression()),
        ]
    )

    X_train, X_test, y_train, y_test = train_test_split(
        X_raw, y, test_size=0.2, random_state=42
    )

    model.fit(X_train, y_train)
    r2 = model.score(X_test, y_test)

    return model, r2, X_raw, y


def build_user_input(df: pd.DataFrame) -> pd.DataFrame:
    """Create a single-row DataFrame from sidebar user input."""
    st.sidebar.header("Enter Member & Workout Details")

    # Use dataset min/max/median to set reasonable slider ranges
    age_min, age_max = int(df["Age"].min()), int(df["Age"].max())
    bmi_min, bmi_max = float(df["BMI"].min()), float(df["BMI"].max())
    fat_min, fat_max = float(df["Fat_Percentage"].min()), float(df["Fat_Percentage"].max())
    water_min, water_max = float(df["Water_Intake (liters)"].min()), float(df["Water_Intake (liters)"].max())
    wf_min, wf_max = int(df["Workout_Frequency (days/week)"].min()), int(df["Workout_Frequency (days/week)"].max())
    exp_min, exp_max = int(df["Experience_Level"].min()), int(df["Experience_Level"].max())
    bpm_min, bpm_max = int(df["Avg_BPM"].min()), int(df["Avg_BPM"].max())
    maxbpm_min, maxbpm_max = int(df["Max_BPM"].min()), int(df["Max_BPM"].max())
    restbpm_min, restbpm_max = int(df["Resting_BPM"].min()), int(df["Resting_BPM"].max())
    dur_min_h, dur_max_h = float(df["Session_Duration (hours)"].min()), float(df["Session_Duration (hours)"].max())

    age = st.sidebar.slider("Age", age_min, age_max, value=int(df["Age"].median()))
    gender = st.sidebar.selectbox("Gender", sorted(df["Gender"].unique()))
    bmi = st.sidebar.slider("BMI", float(bmi_min), float(bmi_max), float(df["BMI"].median()))
    session_hours = st.sidebar.slider(
        "Session Duration (hours)",
        float(dur_min_h),
        float(dur_max_h),
        float(df["Session_Duration (hours)"].median()),
        step=0.1,
    )
    avg_bpm = st.sidebar.slider(
        "Average BPM during workout",
        bpm_min,
        bpm_max,
        int(df["Avg_BPM"].median()),
    )
    max_bpm = st.sidebar.slider(
        "Max BPM during workout",
        maxbpm_min,
        maxbpm_max,
        int(df["Max_BPM"].median()),
    )
    rest_bpm = st.sidebar.slider(
        "Resting BPM",
        restbpm_min,
        restbpm_max,
        int(df["Resting_BPM"].median()),
    )
    workout_type = st.sidebar.selectbox("Workout Type", sorted(df["Workout_Type"].unique()))
    fat_pct = st.sidebar.slider(
        "Body Fat Percentage",
        float(fat_min),
        float(fat_max),
        float(df["Fat_Percentage"].median()),
    )
    water = st.sidebar.slider(
        "Water Intake (liters/day)",
        float(water_min),
        float(water_max),
        float(df["Water_Intake (liters)"].median()),
        step=0.1,
    )
    wf = st.sidebar.slider(
        "Workout Frequency (days/week)",
        int(wf_min),
        int(wf_max),
        int(df["Workout_Frequency (days/week)"].median()),
    )
    exp = st.sidebar.slider(
        "Experience Level (1 = Beginner, 3 = Advanced)",
        int(exp_min),
        int(exp_max),
        int(df["Experience_Level"].median()),
    )

    # Derived features consistent with training
    duration_min = session_hours * 60
    heart_rate = avg_bpm
    hrr = max_bpm - rest_bpm

    data = {
        "Age": [age],
        "Gender": [gender],
        "BMI": [bmi],
        "heart_rate": [heart_rate],
        "HRR": [hrr],
        "duration_min": [duration_min],
        "Workout_Type": [workout_type],
        "Fat_Percentage": [fat_pct],
        "Water_Intake (liters)": [water],
        "Workout_Frequency (days/week)": [wf],
        "Experience_Level": [exp],
    }

    return pd.DataFrame(data)


# -------------------------
# MAIN APP LAYOUT
# -------------------------
def main():
    st.title("Gym Members Exercise – Calories Burned Predictor")
    st.write(
        "Explore the gym members dataset and predict calories burned for new workout sessions."
    )

    df = load_data()
    model, r2, X_raw, y = train_model(df)
    input_df = build_user_input(df)

    tab_predict, tab_explore, tab_model = st.tabs(
        ["🔮 Predict", "📊 Explore Data", "🧠 About the Model"]
    )

    # ---------- PREDICT TAB ----------
    with tab_predict:
        st.subheader("Prediction for Specified Workout")

        st.markdown("### Input Summary")
        st.write(input_df)

        if st.button("Predict Calories Burned"):
            pred = model.predict(input_df)[0]
            st.markdown(
                f"### 🔥 Predicted Calories Burned: **{pred:.1f} kcal**"
            )
            st.caption(
                "This is an estimate based on your inputs and patterns learned from the historical dataset."
            )

    # ---------- EXPLORE DATA TAB ----------
    with tab_explore:
        st.subheader("Dataset Overview")
        st.write(f"Rows: **{df.shape[0]}**, Columns: **{df.shape[1]}**")
        st.dataframe(df.head())

        st.markdown("### Summary Statistics")
        st.write(df.describe())

        # Fat % by Gender
        st.markdown("### Fat % Distribution by Gender")
        fig1, ax1 = plt.subplots(figsize=(6, 4))
        sns.boxplot(x="Gender", y="Fat_Percentage", data=df, ax=ax1)
        ax1.set_title("Fat % Distribution by Gender")
        ax1.set_xlabel("Gender")
        ax1.set_ylabel("Fat Percentage")
        st.pyplot(fig1)

        # Calories by Workout Type
        st.markdown("### Calories Burned by Workout Type")
        fig2, ax2 = plt.subplots(figsize=(7, 4))
        sns.boxplot(x="Workout_Type", y="Calories_Burned", data=df, ax=ax2)
        ax2.set_title("Calories Burned by Workout Type")
        ax2.set_xlabel("Workout Type")
        ax2.set_ylabel("Calories Burned")
        plt.setp(ax2.get_xticklabels(), rotation=0)
        st.pyplot(fig2)

    # ---------- MODEL TAB ----------
    with tab_model:
        st.subheader("Model Performance")
        st.write(f"Test R² (Linear Regression): **{r2:.3f}**")

        st.markdown("### How the Model Works")
        st.write(
            """
            - **Preprocessing**
              - Numeric features are standardized with `StandardScaler`.
              - Categorical features (`Gender`, `Workout_Type`) are one-hot encoded.
            - **Model**
              - A Linear Regression model is trained on engineered features to predict `Calories_Burned`.
            """
        )

        st.markdown("### Features Used")
        st.write(
            """
            - Age
            - Gender
            - BMI
            - Average Heart Rate (`Avg_BPM` → `heart_rate`)
            - Heart Rate Reserve (`Max_BPM − Resting_BPM` → `HRR`)
            - Session Duration (minutes) (`duration_min`)
            - Workout Type (HIIT, Cardio, Strength, Yoga)
            - Fat Percentage
            - Water Intake (liters/day)
            - Workout Frequency (days/week)
            - Experience Level (1–3)
            """
        )

        st.markdown("### Notes & Limitations")
        st.write(
            """
            - Predictions are estimates and do not account for all factors (e.g., sleep, nutrition, stress).
            - The original analysis showed similar performance across genders, but fairness should be monitored as more data is collected.
            """
        )


if __name__ == "__main__":
    main()